### ISSUE TITLE
报错sendToMain "cc-plugin-demo:showPanel" failed, no response received.

### ISSUE THREAD

**Issue by Judu233** [tidys/cc-plugin#2]
按照步骤一次执行，但是执行完cc-plugin serve 命令后，但是一直卡在npm install.....  然后cocos里面是显示了插件菜单，但是一点击就报错sendToMain "cc-plugin-demo:showPanel" failed, no response received.

**Comment by tidys** [comment]
npm install ....
如果node_modules里面有内容，说明已经可以啦，这个是体验的问题，我已经优化了log，npm完成install之后，打印出已经安装完成 https://github.com/tidys/cc-plugin/commit/79798f331942717b945ecf31889d24574cf448d9#r82357445

**Comment by tidys** [comment]
sendToMain failed的问题需要有时间排查下

**Comment by tidys** [comment]
插件名字不合法，不能包含大写字母，否则creator会视为无效的插件
，打开插件面板会触发报错

sendToMain "xxx" failed, no response received


[cc-plugin@2.1.62 之后的版本](https://www.npmjs.com/package/cc-plugin)追加了插件名字的校验，可以规避类似问题
